version: '2'
services:
    pronostics-app:
        image: pronostics
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://pronostics-postgresql:5432/pronostics
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=pronostics-elasticsearch:9300
        ports:
            - 8080:8080
    pronostics-postgresql:
        extends:
            file: postgresql.yml
            service: pronostics-postgresql
    pronostics-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: pronostics-elasticsearch
